// resources/src/screens/AddFood.tsx
import { LinearProgress } from "@mui/material";
import axios from "axios";
import React, { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";

import MealCard from "../components/MealCard";
import { useQuery } from "../hooks/useQuery";
import { Meal } from "../types/meals";

export default function AddFood() {
    const navigate = useNavigate();
    const query = useQuery();
    const mealType = query.get("meal");

    const [consumedMeals, setConsumedMeals] = useState([]);
    const [meals, setMeals] = useState([]);
    const [user, setUser] = useState(null);

    useEffect(() => {
        const fetchData = async () => {
            const consumedMealsDB = await axios.get(
                `/api/consumed_meals/${mealType}`
            );
            const mealsDB = await axios.get(`/api/meals`);
            const userDB = await axios.get(`/api/user`);
            setConsumedMeals(consumedMealsDB.data);
            setMeals(mealsDB.data);
            setUser(userDB.data);
        };
        fetchData();
    }, []);

    const refetchData = async () => {
        const consumedMealsDB = await axios.get(
            `/api/consumed_meals/${mealType}`
        );
        const mealsDB = await axios.get(`/api/meals`);
        setConsumedMeals(consumedMealsDB.data);
        setMeals(mealsDB.data);
    };

    const handleAddMeal = async (meal: Meal) => {
        const response = await axios.post(`/api/consumed_meals`, {
            meal_id: meal.id,
            meal_type: mealType,
            portion: meal.portion,
            portion_unit: meal.portion_unit,
        });
        if (response.status === 200) {
            refetchData();
        }
    };

    const handleRemoveMeals = async (meal: Meal) => {
        const response = await axios.delete(`/api/consumed_meals/${meal.id}`);
        if (response.status === 200) {
            refetchData();
        }
    };

    const handleCustomizePortion = async (meal: Meal) => {
        navigate(`/food/${meal.id}?meal=${mealType}`);
    };

    return (
        <div className="container space-y-4">
            <section className="my-8 flex h-full w-full  items-center space-x-2">
                <Link to="/dashboard">
                    <svg
                        className="h-6 w-6"
                        fill="none"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth="2"
                        viewBox="0 0 24 24"
                        stroke="currentColor"
                    >
                        <path d="M19 12H5M12 19l-7-7 7-7"></path>
                    </svg>
                </Link>
                <h1 className="text-xl font-bold">{mealType!.toUpperCase()}</h1>
            </section>
            <section className="my-8 flex w-full flex-col items-center space-y-4 rounded border border-base-content p-4 text-neutral-content shadow-lg">
                <div className="flex w-full flex-col items-center justify-center space-y-2">
                    <div className="flex w-full items-center justify-between">
                        <h1 className="text-sm">Dalily intake</h1>
                        <h3 className="text-sm"> 800/2200 kcal</h3>
                    </div>
                    <LinearProgress
                        color="inherit"
                        className="w-full text-accent"
                        value={3}
                        variant="determinate"
                        sx={{ zIndex: 0, borderRadius: "4px" }}
                    />

                    {/* <p className="text-sm">
                        {carbs.eaten} / {carbs.goal}g
                    </p> */}
                </div>
                <div className="flex w-full items-center justify-between">
                    <div className="flex w-1/4 flex-col items-center justify-center space-y-2">
                        <h3 className="text-sm">Carbs</h3>
                        <LinearProgress
                            color="inherit"
                            className="w-full text-accent"
                            value={3}
                            variant="determinate"
                            sx={{ zIndex: 0, borderRadius: "4px" }}
                        />

                        {/* <p className="text-sm">
                        {carbs.eaten} / {carbs.goal}g
                    </p> */}
                    </div>
                    <div className="flex w-1/4 flex-col items-center justify-center space-y-2">
                        <h3 className="text-sm">Protein</h3>
                        <LinearProgress
                            color="inherit"
                            className="w-full text-accent"
                            value={3}
                            variant="determinate"
                            sx={{ zIndex: 0, borderRadius: "4px" }}
                        />

                        {/* <p className="text-sm">
                        {carbs.eaten} / {carbs.goal}g
                    </p> */}
                    </div>
                    <div className="flex w-1/4 flex-col items-center justify-center space-y-2">
                        <h3 className="text-sm">fat</h3>
                        <LinearProgress
                            color="inherit"
                            className="w-full text-accent"
                            value={3}
                            variant="determinate"
                            sx={{ zIndex: 0, borderRadius: "4px" }}
                        />

                        {/* <p className="text-sm">
                        {carbs.eaten} / {carbs.goal}g
                    </p> */}
                    </div>
                </div>
            </section>
            {consumedMeals.length > 0 && (
                <section className="my-8">
                    <h1>Consumed meals</h1>
                    <div className="space-y-4">
                        {consumedMeals.map((consumedMeal) => (
                            <MealCard
                                key={consumedMeal.id}
                                {...consumedMeal}
                                remove
                                addRemovePortion={() =>
                                    handleRemoveMeals(consumedMeal)
                                }
                            />
                        ))}
                    </div>
                </section>
            )}
            <section className="my-8">
                <h1>Meals</h1>
                <div className="space-y-4">
                    {meals.length > 0 &&
                        meals.map((meal) => (
                            <MealCard
                                key={meal.id}
                                {...meal}
                                customizePortion={() =>
                                    handleCustomizePortion(meal)
                                }
                                addRemovePortion={() => handleAddMeal(meal)}
                            />
                        ))}
                </div>
            </section>
        </div>
    );
}

// frontend/src/routes/add-food.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { toast } from '@zerodevx/svelte-toast';
	import axios from 'axios';

	let name = '';
	let portion: number;
	let calories: number;
	let carbs: number;
	let protein: number;
	let fat: number;
	let barcode: string;

	let invalidInputs = false;

	const handleSubmit = async () => {
		if (name && portion) {
			invalidInputs = false;
			try {
				const response = await axios.post(`http://fitness-journey.test/api/meals`, {
					name,
					portion,
					calories,
					carbs,
					protein,
					fat,
					barcode
				});

				if (response.status === 200) {
					toast.push('Meal added successfully!');
					setTimeout(() => {
						goto('/dashboard');
					}, 2500);

					// TODO: Ask if user wants to add another meal
				}
			} catch (error) {
				console.log(error);
			}
		} else {
			invalidInputs = true;
		}
	};
</script>

<section class="container bg-accent py-8 drop-shadow-md">
	<div class=" flex h-full w-full items-center justify-center  ">
		<a href="/dashboard" class="mr-auto">
			<svg
				class="h-6 w-6 !stroke-accent-content"
				fill="none"
				stroke-linecap="round"
				stroke-linejoin="round"
				stroke-width="2"
				viewBox="0 0 24 24"
				stroke="currentColor"
			>
				<path d="M19 12H5M12 19l-7-7 7-7" />
			</svg>
		</a>
		<h1 class="ml-24 w-full text-xl font-bold text-accent-content">Add Food</h1>
	</div>
</section>
<div class="container mt-16 flex w-full flex-col items-center justify-center">
	<form class="flex w-full flex-col items-center space-y-4">
		<div class="flex w-full flex-col ">
			<label class="text-xl text-gray-200" for="name"> Name </label>
			<input
				type="text"
				name="Meal"
				class="max-w-xs input w-full bg-neutral text-xl text-neutral-content placeholder:text-xs placeholder:text-gray-400"
				bind:value={name}
			/>
		</div>
		<div class="flex w-full flex-col ">
			<label class="text-xl text-gray-200" for="Kcal"> Kcal </label>
			<input
				type="text"
				name="Kcal"
				class="max-w-xs input w-full bg-neutral text-xl text-neutral-content placeholder:text-xs placeholder:text-gray-400"
				bind:value={calories}
			/>
		</div>
		<div class="flex w-full flex-col ">
			<label class="text-xl text-gray-200" for="Carbs"> Carbs </label>
			<input
				type="text"
				name="Carbs"
				class="max-w-xs input w-full bg-neutral text-xl text-neutral-content placeholder:text-xs placeholder:text-gray-400"
				bind:value={carbs}
			/>
		</div>
		<div class="flex w-full flex-col ">
			<label class="text-xl text-gray-200" for="Protein">Protein </label>
			<input
				type="text"
				name="Protein"
				class="max-w-xs input w-full bg-neutral text-xl text-neutral-content placeholder:text-xs placeholder:text-gray-400"
				bind:value={protein}
			/>
		</div>
		<div class="flex w-full flex-col ">
			<label class="text-xl text-gray-200" for="Fat">Fat </label>
			<input
				type="text"
				name="Fat"
				class="max-w-xs input w-full bg-neutral text-xl text-neutral-content placeholder:text-xs placeholder:text-gray-400"
				bind:value={fat}
			/>
		</div>
		<div class="flex w-full flex-col ">
			<label class="text-xl text-gray-200" for="barcode">barcode </label>
			<input
				type="text"
				name="barcode"
				class="max-w-xs input w-full bg-neutral text-xl text-neutral-content placeholder:text-xs placeholder:text-gray-400"
				bind:value={barcode}
			/>
		</div>
		<div
			class="text-md  container fixed bottom-0 bg-gradient-to-t from-base-100 to-transparent pb-4"
		>
			<button on:click|preventDefault={handleSubmit} class=" btn-main "> Submit Meal </button>
		</div>
	</form>
</div>
