// resources/src/screens/Dashboard.tsx
import React, {
    MouseEventHandler,
    useContext,
    useEffect,
    useState,
} from "react";
import { Head } from "../components/shared/Head";
import CircularProgress, {
    CircularProgressProps,
} from "@mui/material/CircularProgress";
import Box from "@mui/material/Box";
import LinearProgress from "@mui/material/LinearProgress";
import axios from "axios";
import { useNavigate } from "react-router-dom";

// SVG ICONS
import BakeryDiningRoundedIcon from "@mui/icons-material/BakeryDiningRounded";
import AddCircleRoundedIcon from "@mui/icons-material/AddCircleRounded";
import RamenDiningRoundedIcon from "@mui/icons-material/RamenDiningRounded";
import DinnerDiningRoundedIcon from "@mui/icons-material/DinnerDiningRounded";
import FastfoodRoundedIcon from "@mui/icons-material/FastfoodRounded";
import { useAuth } from "../hooks/useAuth";
import { UserContext } from "../contexts/UserContext";
import { useMacros } from "../hooks/useMacros";
import { DropdownMenuButton } from "../components/DropdownMenuButton";

type MealCardProps = {
    title: string;
    foodItems: string[];
    calories: number;
    reccomendedCalories: number;
    icon: React.ReactElement;
    addFoodItem: MouseEventHandler;
};

function MealCard({
    title,
    foodItems,
    calories,
    reccomendedCalories,
    icon,
    addFoodItem,
}: MealCardProps) {
    //    loop through foodItems and add a , after each item except the last one
    const foodItemsList = foodItems.map((item, index) => {
        if (index === foodItems.length - 1) {
            return item;
        } else {
            return `${item}, `;
        }
    });

    return (
        <div
            className="flex h-28 flex-col rounded-md border border-gray-400 bg-base-content shadow-lg"
            onClick={addFoodItem}
        >
            <div className="flex h-full items-center py-3 px-4">
                <figure>{icon}</figure>
                <main className="ml-6 flex w-60 flex-col items-start justify-center">
                    <h1 className="w-full text-base font-semibold">{title}</h1>
                    <p className="w-full truncate text-sm">
                        {foodItems.length
                            ? foodItemsList
                            : `reccomended amount: ${reccomendedCalories} kcal`}
                    </p>
                </main>
                <AddCircleRoundedIcon className="ml-auto " />
            </div>
            <hr className="border border-gray-200" />
            <p className="flex h-max items-end justify-center  py-2 text-center text-sm">
                {calories} kcal
            </p>
        </div>
    );
}

function CircularProgressWithLabel(
    props: CircularProgressProps & { percent: number } & {
        left: number;
    } & {
        size: number;
    } & { thickness: number } & { eaten: number } & { goal: number }
) {
    return (
        <Box
            sx={{
                position: "relative",
                display: "inline-flex",
            }}
        >
            <CircularProgress
                variant="determinate"
                color="inherit"
                sx={{ zIndex: 0 }}
                value={props.percent}
                {...props}
            />
            <CircularProgress
                variant="determinate"
                color="inherit"
                size={props.size}
                thickness={props.thickness}
                value={100}
                sx={{
                    color: "rgba(59,109,114,1)",
                    top: 0,
                    left: 0,
                    bottom: 0,
                    right: 0,
                    position: "absolute",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    zIndex: -10,
                }}
            />
            <CircularProgress
                variant="determinate"
                size={props.size}
                thickness={props.thickness}
                color="warning"
                value={
                    props.eaten - props.goal > 0
                        ? ((props.eaten - props.goal) / props.goal) * 100
                        : 0
                }
                sx={{
                    top: 0,
                    left: 0,
                    bottom: 0,
                    right: 0,
                    position: "absolute",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    zIndex: 10,
                }}
            />
            <Box
                sx={{
                    top: 0,
                    left: 0,
                    bottom: 0,
                    right: 0,
                    position: "absolute",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                }}
            >
                <div className="flex flex-col items-center  text-gray-100">
                    <h1 className="text-3xl">{Math.abs(props.left)}</h1>
                    <h2 className="text-lg">
                        {props.percent > 100 ? "OVER" : "LEFT"}
                    </h2>
                </div>
            </Box>
        </Box>
    );
}

export default function Dashboard() {
    console.log("dashboard rendered");

    const { user, setUser } = useContext(UserContext);
    const {
        protein,
        setProtein,
        proteinPercent,
        setProteinPercent,
        fat,
        setFat,
        fatPercent,
        setFatPercent,
        carbs,
        setCarbs,
        carbsPercent,
        setCarbsPercent,
        calories,
        setCalories,
        caloriesPercent,
        setCaloriesPercent,
    } = useMacros();

    const [consumedMeals, setConsumedMeals] = useState({
        breakfast: [],
        lunch: [],
        dinner: [],
        snacks: [],
    });

    const navigate = useNavigate();

    useEffect(() => {
        // TODO: make this a hook
        const fetchData = async () => {
            const promises = [
                axios.get("/api/consumed_meals/breakfast"),
                axios.get("/api/consumed_meals/lunch"),
                axios.get("/api/consumed_meals/dinner"),
                axios.get("/api/consumed_meals/snacks"),
            ];
            const [breakfast, lunch, dinner, snacks] = await Promise.all(
                promises
            );
            setConsumedMeals({
                breakfast: breakfast.data,
                lunch: lunch.data,
                dinner: dinner.data,
                snacks: snacks.data,
            });
        };
        fetchData();
        setCalories((calories) => ({
            ...calories,
            left: calories.goal - calories.eaten,
            goal: user.calorie_goal,
        }));
        setCarbs((carbs) => ({
            ...carbs,
            left: carbs.goal - carbs.eaten,
            goal: user.carb_goal,
        }));
        setFat((fat) => ({
            ...fat,
            left: fat.goal - fat.eaten,
            goal: user.fat_goal,
        }));
        setProtein((protein) => ({
            ...protein,
            left: protein.goal - protein.eaten,
            goal: user.protein_goal,
        }));
    }, []);

    useEffect(() => {
        const combinedMeals = consumedMeals.breakfast.concat(
            consumedMeals.lunch,
            consumedMeals.dinner,
            consumedMeals.snacks
        );
        const totalCalories = combinedMeals.reduce(
            (acc, meal) => acc + meal.calories,
            0
        );
        const totalCarbs = combinedMeals.reduce(
            (acc, meal) => acc + meal.carbs,
            0
        );
        const totalFat = combinedMeals.reduce((acc, meal) => acc + meal.fat, 0);
        const totalProtein = combinedMeals.reduce(
            (acc, meal) => acc + meal.protein,
            0
        );

        setCalories((calories) => ({
            ...calories,
            eaten: totalCalories,
            left: calories.goal - totalCalories,
        }));
        setCarbs((carbs) => ({
            ...carbs,
            eaten: totalCarbs,
            left: carbs.goal - totalCarbs,
        }));
        setFat((fat) => ({
            ...fat,
            eaten: totalFat,
            left: fat.goal - totalFat,
        }));
        setProtein((protein) => ({
            ...protein,
            eaten: totalProtein,
            left: protein.goal - totalProtein,
        }));
        setFatPercent((totalFat / fat.goal) * 100);
        setCarbsPercent((totalCarbs / carbs.goal) * 100);
        setProteinPercent((totalProtein / protein.goal) * 100);
        setCaloriesPercent((totalCalories / calories.goal) * 100);
    }, [
        consumedMeals.breakfast,
        consumedMeals.lunch,
        consumedMeals.dinner,
        consumedMeals.snacks,
    ]);

    const { logout } = useAuth();

    return (
        <>
            <Head title="Dashboard" />
            <nav className="container flex h-max w-full items-center justify-evenly">
                <div className="w-1/4"></div>
                <h1 className="w-2/4 text-2xl font-bold text-accent-focus ">
                    Fitness journey
                </h1>
                <div className="ml-auto flex w-1/4 items-center justify-end">
                    {/* TODO: make it send a logout function call */}
                    <DropdownMenuButton
                        items={[
                            { name: "My account", navigateTo: "/my-account" },
                            { name: "Log Out" },
                        ]}
                    />
                </div>
            </nav>
            <div className="flex h-screen w-full flex-col items-center">
                <div className="container py-8">
                    <section
                        id="CaloriesSection"
                        className="item-center  flex w-full justify-between text-lg text-gray-200"
                    >
                        <div className=" flex w-1/4 flex-col items-center justify-center">
                            <h1>{calories.eaten}</h1>
                            <h2>EATEN</h2>
                        </div>
                        <div className="flex w-2/4 items-center justify-center">
                            <CircularProgressWithLabel
                                percent={caloriesPercent}
                                left={calories.left}
                                eaten={calories.eaten}
                                goal={calories.goal}
                                size={150}
                                thickness={2}
                                className="text-accent"
                            />
                        </div>
                        <div className=" flex w-1/4 flex-col items-center justify-center">
                            <h1>{calories.burned}</h1>
                            <h2>BURNED</h2>
                        </div>
                    </section>
                    <section className="mt-6 flex w-full justify-between text-lg text-gray-200">
                        <div className="flex w-1/4 flex-col items-center justify-center space-y-2">
                            <h3>Carbs</h3>
                            <LinearProgress
                                color="inherit"
                                className="w-full text-accent"
                                value={carbsPercent}
                                variant="determinate"
                                sx={{ zIndex: 0, borderRadius: "4px" }}
                            />

                            <p className="text-sm">
                                {carbs.eaten} / {carbs.goal}g
                            </p>
                        </div>
                        <div className="flex w-1/4 flex-col items-center justify-center space-y-2">
                            <h3>Potein</h3>
                            <LinearProgress
                                color="inherit"
                                className="w-full text-accent"
                                value={proteinPercent}
                                variant="determinate"
                                sx={{ zIndex: 0, borderRadius: "4px" }}
                            />
                            <p className="text-sm">
                                {protein.eaten} / {protein.goal}g
                            </p>
                        </div>
                        <div className="flex w-1/4 flex-col items-center justify-center space-y-2">
                            <h3>Fat</h3>
                            <LinearProgress
                                color="inherit"
                                className="w-full text-accent"
                                value={fatPercent}
                                variant="determinate"
                                sx={{ zIndex: 0, borderRadius: "4px" }}
                            />
                            <p className="text-sm">
                                {fat.eaten} / {fat.goal}g
                            </p>
                        </div>
                    </section>
                </div>
                <section
                    id="Food"
                    className="item-center mt-8 flex w-full flex-col justify-center bg-base-100 text-lg text-base-200"
                >
                    <div className="container space-y-6">
                        <MealCard
                            title="Breakfast"
                            foodItems={consumedMeals.breakfast.map(
                                (food) => food.name
                            )}
                            calories={consumedMeals.breakfast.reduce(
                                (acc, food) => acc + food.calories,
                                0
                            )}
                            reccomendedCalories={400}
                            icon={<BakeryDiningRoundedIcon />}
                            addFoodItem={() =>
                                navigate("/add-food?meal=breakfast")
                            }
                        />
                        <MealCard
                            title="Lunch"
                            foodItems={consumedMeals.lunch.map(
                                (food) => food.name
                            )}
                            calories={consumedMeals.lunch.reduce(
                                (acc, food) => acc + food.calories,
                                0
                            )}
                            reccomendedCalories={700}
                            icon={<RamenDiningRoundedIcon />}
                            addFoodItem={() => navigate("/add-food?meal=lunch")}
                        />
                        <MealCard
                            title="Dinner"
                            foodItems={consumedMeals.dinner.map(
                                (food) => food.name
                            )}
                            calories={consumedMeals.dinner.reduce(
                                (acc, food) => acc + food.calories,
                                0
                            )}
                            reccomendedCalories={900}
                            icon={<DinnerDiningRoundedIcon />}
                            addFoodItem={() =>
                                navigate("/add-food?meal=dinner")
                            }
                        />
                        <MealCard
                            title="Snack"
                            foodItems={consumedMeals.snacks.map(
                                (food) => food.name
                            )}
                            calories={consumedMeals.snacks.reduce(
                                (acc, food) => acc + food.calories,
                                0
                            )}
                            reccomendedCalories={300}
                            icon={<FastfoodRoundedIcon />}
                            addFoodItem={() => navigate("/add-food?meal=snack")}
                        />
                    </div>
                </section>
            </div>
        </>
    );
}

// src/routes/(nav)/dashboard/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import ProgressRing from '$lib/components/ProgressRing.svelte';
	import MealCard from '$lib/components/MealCard.svelte';
	import { onMount } from 'svelte';
	import { user } from '$lib/stores/userStore';
	import { supabase } from '$lib/supabaseClient';

	// SVG ICONS
	import FoodCroissant from 'svelte-material-icons/FoodCroissant.svelte';
	import Noodles from 'svelte-material-icons/Noodles.svelte';
	import Pasta from 'svelte-material-icons/Pasta.svelte';
	import FoodApple from 'svelte-material-icons/FoodApple.svelte';

	import {
		caloriesBurned,
		caloriesEaten,
		caloriesGoal,
		caloriesPercent,
		caloriesLeft,
		carbsEaten,
		carbsGoal,
		carbsPercent,
		fatEaten,
		fatGoal,
		fatPercent,
		proteinEaten,
		proteinGoal,
		proteinPercent
	} from '$lib/stores/macrosStore.js';
	import {
		consumedBreakfast,
		consumedLunch,
		consumedDinner,
		consumedSnacks,
		meals
	} from '$lib/stores/consumedMeals';

	let consumedMeals;
	let fetchedMeals;

	const calculateRecommendedAmountOfCalories = (percentage: number) => {
		return Math.round((percentage / 100) * $caloriesLeft);
	};

	onMount(async () => {
		const start = new Date();
		start.setHours(0, 0, 0, 0);
		const { data } = await supabase
			.from('consumed_meals')
			.select('meal_type, portion,meals(*)')
			.match({ user_id: $user?.id })
			.gt('created_at', start.toISOString());

		const { data: mealsData } = await supabase
			.from('meals')
			.select('*')
			.match({ is_quick_tracked: false });
		if (data && mealsData) {
			const consumedMeals = {
				breakfast: data
					.filter((meal) => meal.meal_type === 'breakfast')
					.map((meal) => {
						return {
							...meal.meals,
							portion: meal.portion
						};
					}),
				lunch: data
					.filter((meal) => meal.meal_type === 'lunch')
					.map((meal) => {
						return {
							...meal.meals,
							portion: meal.portion
						};
					}),
				dinner: data
					.filter((meal) => meal.meal_type === 'dinner')
					.map((meal) => {
						return {
							...meal.meals,
							portion: meal.portion
						};
					}),
				snacks: data
					.filter((meal) => meal.meal_type === 'snacks')
					.map((meal) => {
						return {
							...meal.meals,
							portion: meal.portion
						};
					})
			};
			$consumedBreakfast = consumedMeals?.breakfast;
			$consumedLunch = consumedMeals?.lunch;
			$consumedDinner = consumedMeals?.dinner;
			$consumedSnacks = consumedMeals?.snacks;
			$meals = mealsData;
		}
	});
</script>

<svelte:head>
	<title>Venato | Dashboard</title>
</svelte:head>

<main class=" w-screen overflow-x-hidden">
	<nav class="container mt-6 flex h-max w-full items-center justify-evenly">
		<h1 class="text-2xl font-bold text-accent">Venato</h1>
	</nav>
	<div class="flex w-full flex-col items-center ">
		<div class="container py-8">
			<section
				id="CaloriesSection"
				class="item-center  flex w-full justify-between text-lg text-neutral-content"
			>
				<div class=" flex w-1/4 flex-col items-center justify-center">
					<h1>{$caloriesEaten}</h1>
					<h2>EATEN</h2>
				</div>
				<div class="flex w-2/4 items-center justify-center">
					<ProgressRing
						radius={150}
						percent={$caloriesPercent}
						percentOver={(($caloriesEaten - $caloriesGoal) / $caloriesGoal) * 100}
						stroke={1}
						number={$caloriesLeft}
						text={`Kcal ${$caloriesPercent > 100 ? 'over' : 'left'}`}
					/>
				</div>
				<div class=" flex w-1/4 flex-col items-center justify-center">
					<h1>{$caloriesBurned}</h1>
					<h2>BURNED</h2>
				</div>
			</section>
			<section class="mt-6 flex w-full justify-between text-lg text-neutral-content">
				<div class="flex w-1/4 flex-col items-center justify-center space-y-2">
					<h3>Carbs</h3>
					<progress class="progress progress-accent w-full" value={$carbsPercent} max="100" />
					<p class="text-sm">
						{$carbsEaten} / {$carbsGoal}g
					</p>
				</div>
				<div class="flex w-1/4 flex-col items-center justify-center space-y-2">
					<h3>Protein</h3>
					<progress class="progress progress-accent w-full " value={$proteinPercent} max="100" />
					<p class="text-sm">
						{$proteinEaten} / {$proteinGoal}g
					</p>
				</div>
				<div class="flex w-1/4 flex-col items-center justify-center space-y-2">
					<h3>Fat</h3>
					<progress class="progress progress-accent w-full " value={$fatPercent} max="100" />
					<p class="text-sm">
						{$fatEaten} / {$fatGoal}g
					</p>
				</div>
			</section>
		</div>
		<section
			id="Food"
			class="item-center mt-8 flex w-full flex-col justify-center text-lg  text-base-200"
		>
			<div class="container space-y-6">
				<MealCard
					title="Breakfast"
					foodItems={$consumedBreakfast}
					calories={$consumedBreakfast?.reduce((acc, food) => acc + food.calories, 0) || 0}
					recommendedCalories={calculateRecommendedAmountOfCalories(22)}
					addFoodItem={() => goto('/track-food/breakfast')}
				>
					<FoodCroissant size={'30'} />
				</MealCard>
				<MealCard
					title="Lunch"
					foodItems={$consumedLunch}
					calories={$consumedLunch?.reduce((acc, food) => acc + food.calories, 0) || 0}
					recommendedCalories={calculateRecommendedAmountOfCalories(33)}
					addFoodItem={() => goto('/track-food/lunch')}
				>
					<Noodles size={'30'} />
				</MealCard>
				<MealCard
					title="Dinner"
					foodItems={$consumedDinner}
					calories={$consumedDinner?.reduce((acc, food) => acc + food.calories, 0) || 0}
					recommendedCalories={calculateRecommendedAmountOfCalories(35)}
					addFoodItem={() => goto('/track-food/dinner')}
				>
					<Pasta size={'30'} />
				</MealCard>
				<MealCard
					title="Snacks"
					foodItems={$consumedSnacks}
					calories={$consumedSnacks?.reduce((acc, food) => acc + food.calories, 0) || 0}
					recommendedCalories={calculateRecommendedAmountOfCalories(10)}
					addFoodItem={() => goto('/track-food/snacks')}
				>
					<FoodApple size={'30'} />
				</MealCard>
			</div>
		</section>
	</div>
</main>

<style>
	.progress-accent {
		--tw-bg-opacity: 1;
		background-color: #4b5563;
	}
</style>
